"use client"

import { Progress } from "@/components/ui/progress"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { AlertCircle, BrainCircuit, User } from "lucide-react"

interface AIDetectorProps {
  code: string
  language: string
  isAnalyzing: boolean
  results: {
    aiProbability: number
    humanProbability: number
    aiPatterns: string[]
    highlightedCode: string
  } | null
}

export default function AIDetector({ code, language, isAnalyzing, results }: AIDetectorProps) {
  return (
    <div className="h-full w-full bg-gray-950 p-4 overflow-auto">
      {isAnalyzing ? (
        <div className="flex flex-col items-center justify-center h-full">
          <h3 className="text-lg mb-4">Analyzing code for AI patterns...</h3>
          <Progress value={Math.random() * 100} className="w-1/2 mb-2" />
          <p className="text-sm text-gray-400">Examining code structure and patterns</p>
        </div>
      ) : results ? (
        <div className="space-y-4">
          <Card className="bg-gray-800 border-gray-700">
            <CardHeader>
              <CardTitle>AI Detection Results</CardTitle>
              <CardDescription>
                Analysis of code patterns and structures to determine AI vs human origin
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex justify-between mb-4">
                <div className="flex items-center">
                  <BrainCircuit className="h-5 w-5 mr-2 text-purple-500" />
                  <span>AI Probability: {results.aiProbability.toFixed(1)}%</span>
                </div>
                <div className="flex items-center">
                  <User className="h-5 w-5 mr-2 text-blue-500" />
                  <span>Human Probability: {results.humanProbability.toFixed(1)}%</span>
                </div>
              </div>

              <Progress
  value={results.aiProbability}
  className="h-2 mb-4 bg-gradient-to-r from-blue-500 to-purple-500"
/>

              <div className="mt-4">
                <h4 className="text-sm font-medium mb-2">Detected AI Patterns:</h4>
                {results.aiPatterns.length > 0 ? (
                  <ul className="list-disc pl-5 space-y-1">
                    {results.aiPatterns.map((pattern, index) => (
                      <li key={index} className="text-sm">
                        {pattern}
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className="text-sm text-gray-400">No specific AI patterns detected</p>
                )}
              </div>
            </CardContent>
          </Card>

          <Card className="bg-gray-800 border-gray-700">
            <CardHeader>
              <CardTitle className="text-base">
                {results.aiProbability > 70 ? (
                  <div className="flex items-center">
                    <AlertCircle className="h-5 w-5 mr-2 text-yellow-500" />
                    High likelihood of AI-generated code
                  </div>
                ) : results.aiProbability > 40 ? (
                  <div className="flex items-center">
                    <AlertCircle className="h-5 w-5 mr-2 text-blue-500" />
                    Moderate likelihood of AI assistance
                  </div>
                ) : (
                  <div className="flex items-center">
                    <User className="h-5 w-5 mr-2 text-green-500" />
                    Likely human-written code
                  </div>
                )}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm mb-4">
                {results.aiProbability > 70
                  ? "This code exhibits strong characteristics of AI-generated content, including consistent formatting, comprehensive implementation, and structured patterns."
                  : results.aiProbability > 40
                    ? "This code shows some signs of AI assistance, but may have been edited or partially written by a human."
                    : "This code appears to be primarily human-written, with natural variations in style and structure."}
              </p>
            </CardContent>
          </Card>
        </div>
      ) : (
        <div className="flex items-center justify-center h-full text-gray-500">
          Click "Detect AI" to analyze if your code was generated by AI
        </div>
      )}
    </div>
  )
}
